### ISSUE TITLE
No sensor data available

### ISSUE THREAD

**Issue by mintyPT** [macmade/Sensors#1] opened 2021-08-19 09:49 UTC
Just launched it and got this

![image](https://user-images.githubusercontent.com/1147911/130047841-58439f49-49f3-46ea-a539-ea0278e1dd2b.png)

This I miss something?

**Comment by TonyVie** [comment] 2021-08-19 09:53
Same for me

mbp 16 2019, macOS 11.5 (20G71)

**Comment by macmade** [comment] 2021-08-19 09:54
Sensors depends on the hardware.  
I built this app on an M1 MacBook Air - I'm no longer on Intel.

**Comment by mintyPT** [comment] 2021-08-19 11:26
I guess it makes sense then since I'm not on a m1.

I would help out but I don't know the first thing about mac apps.

**Comment by Miguel-Bento-Github** [comment] 2021-08-19 13:28
Mac Mini 2020 here, works like a charm.

![Screenshot 2021-08-19 at 15 28 31](https://user-images.githubusercontent.com/51338450/130076945-94c9bbc8-ab0b-4874-9230-a9f1f831f238.png)

**Comment by macmade** [comment] 2023-02-06 18:12
The issue is fixed in version 1.1.0: https://github.com/macmade/Sensors/releases/tag/1.1.0

**Closed as completed by macmade** 2023-02-06 18:12 UTC
